const prefix = (arr: string[]) => arr.map((item) => `hyperupcall/${item}`)

export const categories: Record<
	string,
	{
		entries: string[]
		data: Repo[]
	}
> = {
	Meta: {
		entries: [
			...prefix([
				'hyperupcall',
				'repos',
				'dots',
				'website',
				'blog',
				'slides',
				'containers',
				'infrastructure',
				'awesome-icons',
			]),
		],
		data: [],
	},
	Projects: {
		entries: [
			...prefix([
				'fox-css',
				'fox-night',
				'cactus',
				'cmdcap',
				'dotfox',
				'foxomate',
				'pick-sticker',
				'xdgbasedirectoryspecification.com',
				'toml-subset',
				'libfoxdebug',
				'editorconfig-lint',
				'tree-sitter-tcsh',
				'tree-sitter-bash',
			]),
		],
		data: [],
	},
	'Projects Bash': {
		entries: [
			'hyperupcall/basalt',
			'hyperupcall/awesome-basalt',
			'hyperupcall/autoenv',
			...prefix(['bake', 'woof', 'shelltest', 'hookah', 'choose', 'glue']),
			...prefix([
				'bash-core',
				'bash-object',
				'bash-std',
				'bash-algo',
				'bash-args',
				'bash-semver',
				'bash-str',
				'bash-term',
				'bash-toml',
				'bats-all',
				'bats-assert',
				'bats-core',
				'bats-file',
				'bats-support',
				'themer',
				'salamis',
				'glue',
				'glue-example',
				'glue-store',
			]),
		],
		data: [],
	},
	'Projects Deno': {
		entries: [
			...prefix([
				'config',
				'is_exe',
				'ensure',
				'deno-fox',
				'deno-http',
				'deno-search',
				'deno-debug',
			]),
		],
		data: [],
	},
	'Projects Plugins': {
		entries: [
			'fox-land/remark-insert',
			'fox-land/remark-readme',
			...prefix([
				'babel-improved-piped-pipelines',
				'babel-plugin-improved-gulp-pipelines',
				'babel-plugin-owoifier',
				'eslint-config-fox',
				'hugo-natrium-theme',
				'hexo-theme-fluid',
				'remark-starchart',
				'vscode-hyperupcall',
				'web-input-readline-hotkeys-extension',
			]),
		],
		data: [],
	},
	'Retired Shipped Projects': {
		entries: [
			'eshsrobotics/database-photos',
			'eshsrobotics/website-challenge-2019',
			...prefix([
				'word-finder',
				'periodic-table',
				'fox-suite',
				'FoxModpackRisk',
				'babel-hacklang',
				'hacklang-sucrase',
				'jqa',
				'baeuda',
				'sigag',
				'deno-babel',
				'hackclub-community',
				'tails',
				'tails-projects',
				'portable-workstation',
				'volant',
				'dockerized-mars',
				'dockerized-mmlogic',
			]),
		],
		data: [],
	},
	'Retired Canned Projects': {
		entries: [
			...prefix([
				'periodic-table-v2',
				'template-bash',
				'spectre-css-dark',
				'shell-installer',
				'bm',
				'cliflix',
				'hacktoberno-thanks',
				'plataea',
				'urocyon',
				'urocyon-cookbook',
				'gtk-tic-tac-toe',
				'paper',
				'github-dashboard',
				'awesome-git-hooks',
				'thermopylae',
				'minecraft-bot',
				'marko-feather',
				'node-licenses',
				'proposal-array-last-find-index',
				'sort-package-json',
				'radar',
				'go-logger',
				'compiler-sampler',
			]),
		],
		data: [],
	},
	'Retired Moved Projects': {
		entries: [
			...prefix([
				'dots-bootstrap',
				'dotshellextract',
				'dotshellgen',
				'bash-error',
				'bamboo',
			]),
		],
		data: [],
	},
	$Ignore: {
		entries: [
			'replit-discord/all-seeing-bot',
			'uakotaobi/notes',
			'DataSciClubECC/.github',
			'cs-club-smc/pacman-game',
			'eankeen/blog',
			'gamedevunite-at-smc/fall2021',
			...prefix([
				'repro-typescript-extension-false-positives',
				'asteroids-reloaded',
				'appliance-manager',
				'awesome-oak',
				'deno-template-oak',
				'asteroids-reloaded',
				'my-website',
			]),
		],
		data: [],
	},
}
